### ISSUE TITLE
道理我都懂

### ISSUE THREAD

**Issue by SE-starshippilot** [58191554/CSC3100-Data-Structure-CUHKSZ#1]
但是3100不是数据结构吗

**Comment by 58191554** [comment]
打错字了
________________________________
发件人: Tianhao ***@***.***>
发送时间: 2022年6月16日 14:22
收件人: 58191554/CSC3100-Database-CUHKSZ ***@***.***>
抄送: Subscribed ***@***.***>
主题: [58191554/CSC3100-Database-CUHKSZ] 道理我都懂 (Issue #1)


但是3100不是数据结构吗

―

**Comment by 58191554** [comment]
发现outlook可以收到邮件，好神奇
